services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: timetrac
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d timetrac"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./backend
    environment:
      PORT: 8080
      DATABASE_URL: postgres://app:apppass@db:5432/timetrac?sslmode=disable
      CORS_ORIGIN: http://localhost:8100
      JWT_SECRET: supersecret_change_me
      TZ: Europe/Vienna
    ports:
      - "8087:8080"
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"   # افتح http://localhost:8090
    depends_on:
      - db

volumes:
  dbdata:
